### ISSUE TITLE
power issue with External HDD

### ISSUE THREAD

**Issue by Buhass** [chilledHamza/Hackintosh_Legion_Y530#3]
Hello Boss,

i used your  preconfigured efi on my y530 and everything works awesomely, for now.
only thing is that my External HDD wouldnt work (on wake up from sleep it works (sometimes))
after some research, i found that the SSDT-EC-XUSB should be 2 separate SSDTs (one to power to usb and one to handle data)
i tried to add the SSDT-XUSB  in open core guide but same issue persists.
have you been facing the same, or is there a solution which i accidently missed.

**Comment by chilledHamza** [comment]
> only thing is that my External HDD wouldnt work (on wake up from sleep it works (sometimes))

If I understand correctly Hard Disk is not detected. can you share IOReg before and after attaching hard disk?

> after some research, i found that the SSDT-EC-XUSB should be 2 separate SSDTs (one to power to usb and one to handle data)

I believe you are referring to [SSDT-EC-USBX-LAPTOP](https://github.com/chilledHamza/Hackintosh_Legion_Y530/blob/e03994159d4c25fd9c1e7a42759f6abcd6b7f879/EFI/OC/ACPI/SSDT-EC-USBX-LAPTOP.aml).
- It is possible to combine multiple SSDTs, Technically I can have only one SSDT with all the patches (named SSDT-HACK) and it will just work fine as well. personally I like keep them all separate, easier to modify this way.
- In SSDT-EC-USBX-LAPTOP the USB Power Properties are Injected with [USBX Device in ACPI](https://github.com/dortania/Getting-Started-With-ACPI/blob/b8e37ede5ec68165918cfd611e2afd3075f7fe27/extra-files/decompiled/SSDT-EC-USBX-LAPTOP.dsl#L36-L61)
- I'm not sure about "one to handle data" part, USB ports only need mapping (can be done with SSDT) but I'm using codeless-kext (USBPorts) for USB port mapping.

> have you been facing the same, or is there a solution which i accidentally missed.

I have WD My Passport 4TB and it's perfectly working fine on all three USB-A Ports (1x-RIGHT, 1x-LEFT and 1x-REAR). I never tested it on USB-C port because I don't have any USB-C 3.0 cable and also never mapped the USB-C Port with 3.0 Mode in USBPort.kext properly (don't have any relevant 3.0 USB-C device yet).

Note : USB-C Port in 2.0 mode is mapped and I can use Huawei USB-C earphones without any issue.

**Comment by Buhass** [comment]
i attached the before and after ioreg.


[B&A External Drive.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y530/files/6448067/B.A.External.Drive.zip)
[before & after HDD.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y530/files/6448010/before.after.HDD.zip)

**Comment by chilledHamza** [comment]
> i attached the before and after ioreg.
> 
> [B&A External Drive.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y530/files/6448067/B.A.External.Drive.zip)
> [before & after HDD.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y530/files/6448010/before.after.HDD.zip)

Please attach a copy of IOReg dump (not text file dump of IOReg). also attach a full Problem_reporting files dump when it is working (after sleep/wake cycle or whatever makes it work). 

By the looks of it, there is no external hard disk visible under XHC, and I do see AppleUSBHostResources but you didn't upload full IOReg dump so, I'm not sure if USB Power Properties are injected properly or not.

Which specific port are you trying to connect it to?

Anyway, my hard hard or any other USB device I own works perfectly fine, so doesn't seem like a USB power issue to me.

**Comment by Buhass** [comment]
Ok, so i am unsure what exactly you require, but i imagine  you are asking about the ioreg dump from the ioregistryexplorer.

my laptop was asleep so i plugged the hdd to the back port, and turn it on, it was discovered and shown("export with working HDD"). 

now; usually when i remove it i can not get it back to work, but not sure why i removed and plugged back and it showed up, i tried twice and it worked (it will be shown in red in the "exported with removing 3 times")(same port). 


while in this state, i tried front right port, but nothing is showing up, HDD will Light up and will spin but drive does not show up. i tried left port, and it worked, O.O, but just once, when i unplugged and replugged it stopped working("Export HDD not Working")

then i tried one last time the back port, and it eventually is stopped showing up.

[IOREGEXPLORER.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y530/files/6448403/IOREGEXPLORER.zip)

**Comment by chilledHamza** [comment]
> Ok, so i am unsure what exactly you require, but i imagine you are asking about the ioreg dump from the ioregistryexplorer.

don't worry, got what I needed.

Here are the USB-A Ports for Y530 (each USB3 port has two internal ports) :
- Rear : HS01, SS01
- Left : HS02, SS03
- Right : HS03, SS04

HSxx = USB 2.0 mode, SSxx = USB 3.0 mode

So, In "export with working HDD" we have "FA GOFlex Desk" at USB port HS01 (which is basically rear port, just as you said but 2.0 mode of Rear Port).
Then you say 3 disconnections, but I see 4 disconnection on HS01 Port in file "exported with removing 3 times", you can check it yourself under "XHC" controller in IOReg.
In last file "Export HDD not Working" we have USB Wi-Fi at HS03 (which is right port), and Hard disk was disconnected from HS02 (left port).

In all above cases your hard disk is only detected on HSxx port (which 2.0 mode) instead of SSxx port, because it's supposed to be a USB 3.0 Hard Disk so it should show up under SSxx port. So, either you are using a USB 2.0 cable or your USB cable is 3.0 but broken. so that it only works in 2.0 mode (plus works randomly). May be try with a different USB cable. 

It is working fine on Windows or Linux?
Read/Write speed should be around 100MB+ in USB 3.0 mode.

Note : My "WD My Passport" is always detected on SSxx Port in USB 3.0 mode, unless I use a USB 2.0 cable.

**Comment by Buhass** [comment]
It is working on my  macbook pro 2010. and near instantly when attached plugged 5-10 seconds

On y530, if it ever detects it, it will take 15 to 30 seconds to show up. 

I will try finding another cable, i should have one laying around somewhere.

I could have tried with another external HDD but i dont have currently another one.

I will also try on same laptop but different os.

**Comment by Buhass** [comment]
Ok,  as you said, cable issue.
i tried another cable and it is now working perfectly.
i dismissed it earlier because it was working on the other laptop, on all ports, without an issue.
anyhow, thank you very much for your kind support and awesome work.

**Comment by chilledHamza** [comment]
> Ok, as you said, cable issue.

I suspected it because it was only working in USB 2.0 mode. plus if it was USB Power issue Hard disk won't work at all, no matter what you try.

> i tried another cable and it is now working perfectly.

Great to hear that.

> i dismissed it earlier because it was working on the other laptop, on all ports, without an issue.

It works on MacBook Pro possibly because ports on MacBook Pro (2010) are only USB 2.0. One or more wires that are responsible for 3.0 Mode are broken/damaged and 3.0 Mode is completely ignored by your MacBook Pro, so no issue there.

> anyhow, thank you very much for your kind support and awesome work.

Glad i could help.

Work is not mine for the most part, Thanks to the Hackintosh community and great developers at [Acidanthera](https://github.com/acidanthera).

The only special thing i did is [Num Lock Support VoodooPS2](https://github.com/acidanthera/VoodooPS2/pull/37), not really special just a simple modification to fix the mysterious NumLock issue.
